# Generated by Django 3.2.11 on 2023-02-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20230204_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=500)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
